model_name: "yolo_seg"
model_path: "../weights/yolo/yolov8s-seg.onnx"
framework: "ONNX"
# framework: "TensorRT"
input_size: [640,640]
conf_thres: 0.25
nms_thres: 0.65
seg_size: [160, 160]
seg_channels: 32