model_name: "crnn"
model_path: "../weights/crnn/crnn.onnx"
framework: "ONNX"
# framework: "TensorRT"
input_size: [100,32]  # (width, height)
alphabet: "0123456789abcdefghijklmnopqrstuvwxyz"
output_size: 26